typelevel/algebra

README.md
Also use only header names instead of full URLs in links to make it a
bit less brittle (helps with multiple branches, forks, etc).
=> Fix algebraic properties link

core/src/main/scala/algebra/CommutativeSemigroup.scala, core/src/main/scala/algebra/Semigroup.scala, core/src/main/scala/algebra/ring/Additive.scala, core/src/main/scala/algebra/ring/Multiplicative.scala
My argument here is that we have two ways of specifying commutativity: 1) in the type system, 2) with a method on an instance. There is the possibility there could be badly behaved instances that don't agree with these two. Moreover, it just seems more elegant to have one way.
This replaces the methods on the instances with methods on the objects that check isInstanceOf. All the old use cases are supported, but with a new method.
In Spire, you could implement you accessors in the same way if you are wrapping an Algebra object as a Spire object, so I don't think you'll lose anything.
=> Remove isCommutative/hasCommutative

core/src/main/scala/algebra/BoundedSemilattice.scala, core/src/main/scala/algebra/CommutativeGroup.scala, core/src/main/scala/algebra/CommutativeMonoid.scala, core/src/main/scala/algebra/CommutativeSemigroup.scala, core/src/main/scala/algebra/Group.scala, core/src/main/scala/algebra/Monoid.scala, core/src/main/scala/algebra/Semigroup.scala, core/src/main/scala/algebra/Semilattice.scala, core/src/main/scala/algebra/lattice/Bool.scala, core/src/main/scala/algebra/lattice/BoundedJoinSemilattice.scala, core/src/main/scala/algebra/lattice/BoundedLattice.scala, core/src/main/scala/algebra/lattice/BoundedMeetSemilattice.scala, core/src/main/scala/algebra/lattice/Heyting.scala, core/src/main/scala/algebra/lattice/JoinSemilattice.scala, core/src/main/scala/algebra/lattice/Lattice.scala, core/src/main/scala/algebra/lattice/MeetSemilattice.scala, core/src/main/scala/algebra/number/IsReal.scala, core/src/main/scala/algebra/number/NRoot.scala, core/src/main/scala/algebra/number/Signed.scala, core/src/main/scala/algebra/ring/Additive.scala, core/src/main/scala/algebra/ring/CommutativeRig.scala, core/src/main/scala/algebra/ring/CommutativeRing.scala, core/src/main/scala/algebra/ring/EuclideanRing.scala, core/src/main/scala/algebra/ring/Field.scala, core/src/main/scala/algebra/ring/Multiplicative.scala, core/src/main/scala/algebra/ring/Rig.scala, core/src/main/scala/algebra/ring/Ring.scala, core/src/main/scala/algebra/ring/Rng.scala, core/src/main/scala/algebra/ring/Semiring.scala
The only places where we still specialize on these types is in
Eq/PartialOrder/Order, where we specialize on everything.
This is because these type classes have much wider usage, and
also because it's likely that users will want to define instances
for case classes and other compound types which might want to
make use of specialized instances for Char, Byte, etc.
Resolves #24.
=> Remove Boolean, Byte, and Short specialization from most things.

laws/src/main/scala/algebra/laws/GroupLaws.scala, laws/src/main/scala/algebra/laws/LatticeLaws.scala, laws/src/main/scala/algebra/laws/LatticePartialOrderLaws.scala, laws/src/main/scala/algebra/laws/LogicLaws.scala, laws/src/main/scala/algebra/laws/OrderLaws.scala, laws/src/test/scala/algebra/laws/LawTests.scala
Includes and supersedes #36, which suffered from a suboptimal use of bases.
=> Refactor laws to use bases correctly

build.sbt, laws/src/main/scala/algebra/laws/BaseLaws.scala
This change means that subprojects will inherit the root
build.sbt settings. Since this was always the intention,
this fixes the build.
Resolves #40.
=> Fix root build.sbt set up.

core/src/main/scala/algebra/Eq.scala
These changes were ported here from the 'hash' PR (#38).
This commit adds an implicit from Eq[A] => Equiv[A].
It also adds missing @sp annotations.
=> Make algebra.Eq[A] compatible with scala.math.Equiv[A].

build.sbt
This is a small correction to my #45 yesterday. I'd set up automatic API mapping to work for dependencies, but not to publish the metadata for algebra itself. I've confirmed that this fix gets the right metadata into the right POMs.
=> Publish API mappings metadata

laws/shared/src/test/scala/algebra/laws/LawTests.scala, std/shared/src/main/scala/algebra/std/all.scala, std/shared/src/main/scala/algebra/std/unit.scala
Mostly I wanted the `Order` instance for `Unit`. The use-case is that in
some tests we want to check if something two instances of
`Error Xor Unit` are equal, and the derived `Eq` instance for `Xor`
needs an `Eq` instance for both sides.
I have no idea whether the `CommutativeRig[Unit]` is a good idea or is
useful. It seems to be law-abiding though. Let me know if you want me to
rip it out.
=> Add Unit instances

std/shared/src/main/scala/algebra/std/unit.scala
The `combineAllOption` override is per a [suggestion](https://github.com/non/algebra/pull/87#discussion_r41585052) from @johnynek.
=> Override repeatedCombineN and combineAllOption for Unit algebra

build.sbt, core/src/main/scala/algebra/Band.scala
fixes #90 
Question: should Band and Semilattice use just Int, Long? Looks like most or all of algebra.lattice does this (even though you could make a lattice of Doubles/Floats with max/min).
=> Fix band specialization

build.sbt, core/src/main/scala/algebra/lattice/Bool.scala, core/src/main/scala/algebra/lattice/Heyting.scala
=> Remove asCommutativeRing from Heyting

core/src/main/scala/algebra/lattice/Bool.scala, laws/shared/src/test/scala/algebra/laws/LawTests.scala
This commit makes sure we run our law tests on the ring
produced by Bool[Boolean].asCommutativeRing.
We might want to audit other typeclass-producing methods
to ensure that we do at least some law-checking on those
instances as well.
Review by @TomasMikula and @johnynek.
=> Fix bug in .asCommutativeRing, and ensure it is correct.

core/src/main/scala/algebra/lattice/Bool.scala, core/src/main/scala/algebra/lattice/GenBool.scala, core/src/main/scala/algebra/ring/BoolRing.scala, core/src/main/scala/algebra/ring/BoolRng.scala, laws/shared/src/main/scala/algebra/laws/LogicLaws.scala, laws/shared/src/main/scala/algebra/laws/RingLaws.scala, laws/shared/src/test/scala/algebra/laws/LawTests.scala, std/src/main/scala/algebra/std/set.scala
This is a work in progress on topless Bool/BoolRing (#107), subject to some renaming. In this version I used the names `GenBool` for _generalized Boolean algebra_ and `without(a, b)` for `a\b` (relative complement of b with respect to a).
=> Add BoolRng and GenBool. Resolves #107.

core/src/main/scala/algebra/ring/BoolRing.scala, core/src/main/scala/algebra/ring/CommutativeRing.scala, core/src/main/scala/algebra/ring/EuclideanRing.scala, core/src/main/scala/algebra/ring/Field.scala, core/src/main/scala/algebra/ring/Ring.scala
It seemed like an oversight that `object Ring` did not extend `RingFunctions`.
=> Let Ring and CommutativeRing companions extend RingFunctions.

core/src/main/scala/algebra/Order.scala
Override the `reverse` implementation in the result of `Order.reverse`
to simply return the original `Order` instance.
=> Override reverse in Order.reverse value

core/src/main/scala/algebra/Order.scala, laws/shared/src/test/scala/algebra/laws/LawTests.scala
This provides a conversion from `scala.math.Ordering` to
`algebra.Order`.
I might be abusing the `extraTag` form of the `laws` function, I'm not
sure. If I don't provide a label then I get a duplicate test name error.
=> Add Order.fromOrdering method

core/src/main/scala/algebra/CommutativeGroup.scala, core/src/main/scala/algebra/CommutativeMonoid.scala, core/src/main/scala/algebra/CommutativeSemigroup.scala, core/src/main/scala/algebra/Group.scala, core/src/main/scala/algebra/Monoid.scala, core/src/main/scala/algebra/Semigroup.scala, lattice/src/main/scala/algebra/lattice/Bool.scala, lattice/src/main/scala/algebra/lattice/BoundedDistributiveLattice.scala, lattice/src/main/scala/algebra/lattice/BoundedJoinSemilattice.scala, lattice/src/main/scala/algebra/lattice/BoundedLattice.scala, lattice/src/main/scala/algebra/lattice/BoundedMeetSemilattice.scala, lattice/src/main/scala/algebra/lattice/DistributiveLattice.scala, lattice/src/main/scala/algebra/lattice/GenBool.scala, lattice/src/main/scala/algebra/lattice/Heyting.scala, lattice/src/main/scala/algebra/lattice/JoinSemilattice.scala, lattice/src/main/scala/algebra/lattice/Lattice.scala, lattice/src/main/scala/algebra/lattice/MeetSemilattice.scala, ring/src/main/scala/algebra/ring/Additive.scala, ring/src/main/scala/algebra/ring/BoolRng.scala, ring/src/main/scala/algebra/ring/CommutativeRig.scala, ring/src/main/scala/algebra/ring/Field.scala, ring/src/main/scala/algebra/ring/Multiplicative.scala, ring/src/main/scala/algebra/ring/Rig.scala, ring/src/main/scala/algebra/ring/Ring.scala, ring/src/main/scala/algebra/ring/Rng.scala, ring/src/main/scala/algebra/ring/Semiring.scala
fixes #110 
This uncovered one bug: `CommutativeRig` had `AdditiveGroupFunctions` but that would never have worked for any `Rig` because it is not a group.
Also on a personal note: I prepared and submitted this PR over the state of Colorado on a flight to New Jersey.
=> Add parameters to all functions that extend/are extended

std/src/main/scala/algebra/std/set.scala
At least in case of scala.collection.immutable.HashSet, diff is a tree/tree
operation, whereas -- removes all elements of rhs from lhs one by one. So
diff is much more efficient.
I did this change (tree/tree operations) to s.c.i.HashSet for 2.11. I also think that it would be a good idea to have xor defined in s.c.i.Set for 2.12.
https://github.com/scala/scala/blob/v2.11.7/src/library/scala/collection/immutable/HashSet.scala#L1
=> Use diff instead of -- for set difference

laws/jvm/src/test/scala/algebra/laws/LawTestsJvm.scala, laws/shared/src/main/scala/algebra/laws/CheckSupport.scala, laws/shared/src/test/scala/algebra/laws/LawTests.scala, laws/shared/src/test/scala/algebra/laws/Rat.scala
Also moved Rat arbitrary directly into Rat companion object. CheckSupport
is now empty. Remove?
Implements #135
=> Moved Rat into algebra.laws test scope

std/src/main/scala/algebra/std/all.scala
This commit changes the package object `algebra.std.all` to extend a new `AllInstances` trait instead of directly extending a lot of `*Instances` traits. This shouldn't change the behavior of `algebra.std.all`, but makes it possible to extend the new `AllInstances` trait in a package object in client code (e.g., if a user wants to have all instances visible by default in their packages). (This is similar to the `cats.std.AllInstances` trait in [typelevel/cats](https://github.com/typelevel/cats).)
=> Add algebra.std.AllInstances trait

laws/jvm/src/main/scala/algebra/laws/Platform.scala, laws/shared/src/main/scala/algebra/laws/IsSerializable.scala, laws/shared/src/test/scala/algebra/laws/LawTests.scala
Here's a much simpler (in terms of required implementation changes and ease of use) solution to #123. To skip serialization for a block of tests, just pass a thunk to `withoutSerialization`:
```scala
withoutSerialization {
laws[OrderLaws, Boolean].check(_.order)
}
```
I think this should solve our immediate issue of making the tests reusable for non-serializable instances.
=> use dynamic variable to control serialization tests

laws/shared/src/test/scala/algebra/laws/LawTests.scala, std/src/main/scala/algebra/std/list.scala
Fixes #118.
Note that if we want to support "pairwise instances" for additive/multiplicative semigroups for lists they would be really easy to do (treating uneven lengths as one/zero padded).
=> Add Eq and PartialOrder instances for List.

ring/src/main/scala/algebra/ring/Additive.scala, ring/src/main/scala/algebra/ring/Multiplicative.scala, std/src/main/scala/algebra/std/map.scala
We noticed an issue in cats-kernel where operations over Maps were
incredibly slow. This commit ports those fixes over here, where our
additive/multiplicative monoids experienced the same issues.
Review by @johnynek
=> Improve the performance of Map's algebras.

README.md
I just pushed 0.5.0 to Sonatype, so this PR will update the version in our README.
I also *linkified* the contributor names, rephrased some paragraphs, and added some code blocks to other parts of the README.
I think 0.5.0 should be a candidate for where we start our MiMA compatibility requirements. Here's my proposal for what happens next:
1. @non, @tixxit, @rklaehn, and others will get a Spire branch working that uses *algebra-0.5.0*.
1. We test that Spire branch to be sure that we don't see major problems with our benchmarks.
1. @johnynek and others optionally do the same thing for Algebird.
1. If needed, we make changes to *cats-kernel* and *algebra*, re-release, goto (1).
1. We all agree that we are happy with *cats-kernel* and *algebra* in their current form.
1. We freeze …
=> Add 0.5.0 release to readme and do some cleanup.

core/src/main/scala/algebra/lattice/Bool.scala
If we use `super` in the implementation of a specialized trait it can
cause problems for implementing classes downstream. I hit this bug [1]
when trying to get Spire using Algebra.
[1] https://issues.scala-lang.org/browse/SI-8431
=> Work-around for SI-8431.

core/src/main/scala/algebra/ring/Additive.scala
We missed these, so converting to cats-kernel types would lose the optimizations for sequences.
=> Add combineAll to Additive algebras

.travis.yml, README.md, build.sbt, project/plugins.sbt
I copied the setup from tixxit/delimited - I think this should just ~work. I've also updated the buttons in the README to point to typelevel/aglebra now.
=> Add scoverage and report results to codecov.io

README.md
I nominated both of them, the existing maintainers were unanimous in
agreeing to offer maintainership to them, and they both accepted.
I've also increased number of sign-offs needed (N) from 1 to 2.
With seven maintainers we should be able to meet this requirement,
even if some of us are less active than others (for many significant
PRs we've already done this).
If this ends up being too much of a burden we can reduce N back to 1.
=> Add Rüdiger and Tomas to the list of maintainers.

core/src/main/scala/algebra/instances/bigDecimal.scala, core/src/main/scala/algebra/instances/double.scala, core/src/main/scala/algebra/instances/float.scala, core/src/main/scala/algebra/ring/Field.scala, laws/src/test/scala/algebra/laws/LawTests.scala, laws/src/test/scala/algebra/laws/Rat.scala
The quotmod operation is uniquely defined in fields; this PR provides the correct implementation for Field.
This fixes the BigDecimal, Float, Double instances so that they are lawful (the test Rat instance was correct).
However, as we do not implement `euclideanFunction` in algebra, and the BigDecimal, Float and Double are partially tested, the incorrect behavior did not fail any tests --- and introducing failing tests requires quite a bit of infrastructure (see #172).
Note: there is a substantial impact on Spire as the operator `%` correspond to `EuclideanRing.mod`. Before the change, the incorrect instance gives `3.14 % 2 = 0.14`; this behavior is consistent with the scala stdlib syntax. After the change, `3.14 % 2 = 0`. Thus, `%` should be implemented using another type (see `tquotmod` …
=> Corrects EuclideanRing instances.

build.sbt, core/src/main/scala/algebra/instances/bigDecimal.scala, core/src/main/scala/algebra/instances/bigInt.scala, core/src/main/scala/algebra/instances/byte.scala, core/src/main/scala/algebra/instances/double.scala, core/src/main/scala/algebra/instances/float.scala, core/src/main/scala/algebra/instances/int.scala, core/src/main/scala/algebra/instances/long.scala, core/src/main/scala/algebra/instances/short.scala, core/src/main/scala/algebra/ring/Ring.scala, core/src/test/scala/algebra/ring/RingTest.scala, laws/src/main/scala/algebra/laws/RingLaws.scala, laws/src/test/scala/algebra/laws/Rat.scala
This is similar to `fromInt`, but works with larger numbers. There is a default implementation that is based on `fromInt`, but this method is easily implementable by all our instances that also override `fromInt`.
=> Add Ring#fromBigInt

laws/src/main/scala/algebra/laws/RingLaws.scala
This adds a test for `fromDouble` - it uses the more brute-force version where we convert the Double to a BigDecimal, use that to extract a numerator/denominator, then use `Ring.fromBigInt` on both and divide.
=> Add test for Field.fromDouble.

core/src/main/scala/algebra/ring/Field.scala, core/src/main/scala/algebra/ring/Ring.scala
e.g. in Spire DivisionRing. The code is quite heavy in bit tricks that are difficult to verify, so I'd like to avoid duplication.
=> Split Field.fromDouble to enable reuse.

core/src/main/scala/algebra/instances/bigDecimal.scala, laws/src/main/scala/algebra/laws/RingLaws.scala, laws/src/test/scala/algebra/laws/FPApprox.scala, laws/src/test/scala/algebra/laws/LawTests.scala
This tests the `Field` instances for `Float`, `Double` and `BigDecimal` in a bit of a sneaky way. Rather than test them directly, it uses a `FPApprox` wrapper type. This exercises the underlying `Field` to handle the regular operations, but also maintains an error bound on the approximation. The `Eq` instance for `FPApprox[A]` will return true for any 2 numbers that could be equal, given their error bounds. Of course, there are more subtleties than that:
The numbers occasionally underflow, which causes all sorts of annoying problems. So, we also have to occasionally check if values after multiplications are near-zero and, if so, bump them back up to a very small, but useable number.
The numbers occasionally overflow to infinity, at which point the game is lost, since we soon start getting …
=> Test field laws for Float/Double/BigDecimal.

README.md, build.sbt
Reverts typelevel/algebra#216
I'm not sure why the old links broke in the first place; regardless, they work again now.
=> Revert "Fix homepage"

CODE_OF_CONDUCT.md, README.md
Typelevel has [switched to the Scala Code of Conduct](https://typelevel.org/blog/2019/05/01/typelevel-switches-to-scala-code-of-conduct.html).  This makes it explicit for algebra.
=> Add the Scala Code of Conduct

README.md, build.sbt, docs/src/main/tut/index.md
1.0.1 dropped Scala 2.10 support. I've also clarified that in its current form Algebra is not completely dependency-less.
=> Post-2.10 cleanup
